package main

func main() {
    robot := NewRobot(Table{0,0,4,4})
    robot.Place(1,1,"NORTH")
    robot.Report()
    robot.Move()
    robot.Report()
    robot.Right()
    robot.Report()
    robot.Right()
    robot.Report()
    robot.Right()
    robot.Report()
    robot.Right()
    robot.Report()
    robot.Left()
    robot.Report()
    robot.Move()
    robot.Report()
    robot.Move()
    robot.Report()
    robot.Move()
    robot.Report()
    robot.Move()
    robot.Report()
    robot.Move()
    robot.Report()
    robot.Move()
    robot.Report()
    robot.Move()
    robot.Report()
    robot.Move()
    robot.Report()
    robot.Move()
    robot.Report()
} 
